### ISSUE TITLE
The word list is not among resources

### ISSUE THREAD

**Issue by Coding-Enthusiast** [AngeloMetal/booknemonic#1]
Your word list path is hard coded and can not be used by others. The solution is simple, you can replace the entire following part 
https://github.com/AngeloMetal/booknemonic/blob/ad1a5579d1bf835c575e01761965025243f9eb2b/BIP0039.cs#L305-L331 
with this single line  

```csharp
return Autarkysoft.Bitcoin.ImprovementProposals.BIP0039.GetAllWords(Autarkysoft.Bitcoin.ImprovementProposals.BIP0039.WordLists.English);
```

**Comment by AngeloMetal** [comment]
About that, I don't use any txt file. Word list is the **allEnglishWords** .  I just forgot to remove that line from BIP0039.cs. Why do I use this **string allEnglishWords = "abandon,ability,able,about,above....zebra,zero,zone,zoo"** ? Well I tried to get your english wordlist, but failed. I kept getting "Word list was not found."

**Comment by Coding-Enthusiast** [comment]
It's probably because there are certain conflicts within your code which I just noticed. You have copied both the class name and the namespace name when you were copying the code. The compiler can not decide when you call `Autarkysoft.Bitcoin.ImprovementProposals.BIP0039.GetAllWords` you are calling the method in your own code or the method in the library called "Autarkysoft.Bitcoin". Fixing your namespace should solve this issue.
Change this (and any similar one)
https://github.com/AngeloMetal/booknemonic/blob/ad1a5579d1bf835c575e01761965025243f9eb2b/BIP0039.cs#L15
to `namespace Booknemonic`

**Comment by AngeloMetal** [comment]
It seems that this was the fault. I replaced the `namespace Autarkysoft.Bitcoin.ImprovementProposals` with `namespace Booknemonic` and it works fine now and faster! The previous **allEnglishWords** was slower, because it had to parse the entire string and then start checking if the word exists. I think I'll correct some mistakes I just saw on Encrypt.cs and I'll reupload the files. Thank you once again mr. Coding Enthusiast!
